apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: gitops-poc-cluster
  region: us-east-1
  version: "1.30"
managedNodeGroups:
  - name: free-tier-nodes
    instanceType: t3.micro      # Free Tier eligible instance type
    desiredCapacity: 2          # Minimal nodes needed to handle ArgoCD + Nginx
    minSize: 1
    maxSize: 2
    volumeSize: 10              # Reduced from 20GB to save on EBS disk costs
